<a href="https://colab.research.google.com/github/khalidshanto/khalidshanto/blob/main/S%26M_Assignment_2_id_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
# importing necessary libraries.
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
# Run the code twice.
matrix1 = np.random.randint(1, 51, size=(3, 3))
print("The Matrix:\n",matrix1)

The Matrix:
 [[50  5 50]
 [43 44 41]
 [41 17 40]]


In [21]:
  #With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.
np.random.seed(10)
matrix2 = np.random.randint(1, 51, size=(3, 3))
print("The Matrix:\n",matrix2)

The Matrix:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [22]:
#  Without setting a seed, allowing random values to change each time.
np.random.seed(None)
non_seeded_matrix = np.random.randint(1, 51, (3, 3))
print("\nMatrix without fixed seed:\n", non_seeded_matrix)


Matrix without fixed seed:
 [[42 20 16]
 [14 47  8]
 [40  5  1]]


In [ ]:
 #Observe and explain the differences in outputs. (in a different cell as text).

1.	np.random.seed(10) in the first matrix guarantees that the initial random numbers will always be the same each time the code executes.

2.	We can observe that "np.random.seed()" was used in this instance; nevertheless, because "None" appears in the aforementioned function, the code with no seed value produces a random value for the nonseeded matrix (matrix 3) each time it is executed.

3.Why seed value 10?
The rationale behind selecting "10" as the seed value is that it implies that any number, specifically those falling between 0 and 9, will be utilized as the seed.
This guarantees that the random values will not change.
